apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a302nk1ny-python
  janus-idp.io/tekton: a302nk1ny-python
  backstage.io/kubernetes-id: a302nk1ny-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a302nk1ny-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
